/**
 * End-to-end tests for League Mode v1.
 *
 * All tests are tagged with @league and focus on navigation and page-load
 * verification only — no full season creation flows that require many form steps.
 *
 * Routes under test:
 *   /leagues             → LeaguesHubPage
 *   /leagues/new         → LeagueSetupWizard
 */

import { expect, test } from "@playwright/test";

import { resetAppState } from "../utils/helpers";

test.describe("League Mode", () => {
  test.beforeEach(async ({ page }) => {
    await resetAppState(page);
  });

  // ---------------------------------------------------------------------------
  // 1. Home screen — league teaser section is always visible
  // ---------------------------------------------------------------------------

  test("home screen shows the league play teaser section", { tag: "@league" }, async ({ page }) => {
    await expect(page.getByTestId("league-play-teaser")).toBeVisible({ timeout: 15_000 });
  });

  // ---------------------------------------------------------------------------
  // 2. Home → /leagues navigation via "Start a Season" button
  // ---------------------------------------------------------------------------

  test(
    "clicking Start a Season on the home screen navigates to /leagues",
    { tag: "@league" },
    async ({ page }) => {
      const browseBtn = page.getByTestId("home-browse-leagues-button");
      await expect(browseBtn).toBeVisible({ timeout: 15_000 });
      await browseBtn.click();

      await expect(page).toHaveURL(/\/leagues$/, { timeout: 15_000 });
      await expect(page.getByTestId("leagues-hub")).toBeVisible({ timeout: 15_000 });
    },
  );

  // ---------------------------------------------------------------------------
  // 3. Leagues hub — empty state (fresh app, no seasons, no custom teams)
  // ---------------------------------------------------------------------------

  test(
    "leagues hub shows an empty-state CTA on a fresh app with no seasons",
    { tag: "@league" },
    async ({ page }) => {
      await page.goto("/leagues");

      // The hub container must always be present after loading.
      await expect(page.getByTestId("leagues-hub")).toBeVisible({ timeout: 15_000 });

      // In the empty state (no seasons, no custom teams) the page shows two CTAs:
      // one to build the first team and one to start an all-autogen season.
      await expect(page.getByTestId("hub-build-first-team")).toBeVisible({ timeout: 10_000 });
      await expect(page.getByTestId("hub-start-autogen")).toBeVisible({ timeout: 10_000 });
    },
  );

  // ---------------------------------------------------------------------------
  // 4. Leagues hub — "Start a Season (all autogenerated)" navigates to wizard
  // ---------------------------------------------------------------------------

  test(
    "clicking Start a Season (all autogenerated) navigates to /leagues/new",
    { tag: "@league" },
    async ({ page }) => {
      await page.goto("/leagues");
      await expect(page.getByTestId("leagues-hub")).toBeVisible({ timeout: 15_000 });

      await page.getByTestId("hub-start-autogen").click();

      await expect(page).toHaveURL(/\/leagues\/new/, { timeout: 15_000 });
      await expect(page.getByTestId("league-setup-wizard")).toBeVisible({ timeout: 15_000 });
    },
  );

  // ---------------------------------------------------------------------------
  // 5. Setup wizard loads at /leagues/new
  // ---------------------------------------------------------------------------

  test(
    "navigating to /leagues/new shows the league setup wizard",
    { tag: "@league" },
    async ({ page }) => {
      await page.goto("/leagues/new");

      await expect(page.getByTestId("league-setup-wizard")).toBeVisible({ timeout: 15_000 });
    },
  );

  // ---------------------------------------------------------------------------
  // 6. Setup wizard can be dismissed — close button returns to leagues hub
  // ---------------------------------------------------------------------------

  test(
    "closing the setup wizard navigates back to /leagues",
    { tag: "@league" },
    async ({ page }) => {
      // Arrive at the wizard from the hub so the history stack has /leagues in it.
      await page.goto("/leagues");
      await expect(page.getByTestId("leagues-hub")).toBeVisible({ timeout: 15_000 });

      await page.getByTestId("hub-start-autogen").click();
      await expect(page.getByTestId("league-setup-wizard")).toBeVisible({ timeout: 15_000 });

      // The ModalShell renders a close button with aria-label="Close dialog".
      const closeBtn = page.getByRole("button", { name: /close dialog/i });
      await expect(closeBtn).toBeVisible({ timeout: 10_000 });
      await closeBtn.click();

      // After closing, the browser should navigate back to the leagues hub.
      await expect(page.getByTestId("leagues-hub")).toBeVisible({ timeout: 15_000 });
    },
  );

  // ---------------------------------------------------------------------------
  // 7. Direct URL navigation — /leagues renders the hub
  // ---------------------------------------------------------------------------

  test(
    "navigating directly to /leagues renders the leagues hub page",
    { tag: "@league" },
    async ({ page }) => {
      await page.goto("/leagues");

      await expect(page.getByTestId("leagues-hub")).toBeVisible({ timeout: 15_000 });
    },
  );

  // ---------------------------------------------------------------------------
  // 8. Leagues hub back button returns to the home screen
  // ---------------------------------------------------------------------------

  test(
    "back button on the leagues hub navigates back to the home screen",
    { tag: "@league" },
    async ({ page }) => {
      // Build the history stack: home → /leagues.
      await expect(page.getByTestId("home-screen")).toBeVisible({ timeout: 15_000 });
      const browseBtn = page.getByTestId("home-browse-leagues-button");
      await browseBtn.click();
      await expect(page.getByTestId("leagues-hub")).toBeVisible({ timeout: 15_000 });

      // The hub always renders a "← Back" button.
      const backBtn = page.getByRole("button", { name: /go back/i });
      await expect(backBtn).toBeVisible({ timeout: 10_000 });
      await backBtn.click();

      await expect(page.getByTestId("home-screen")).toBeVisible({ timeout: 15_000 });
    },
  );
});
