import * as React from "react";

import { makeCustomTeamStore } from "@feat/customTeams/storage/customTeamStore";
import { generateLeagueTeams } from "@feat/league/autogen/generateLeagueTeams";
import { createSeason, quickStart } from "@feat/league/storage/leagueStore";
import { useActiveSeason } from "@feat/leagues/hooks/useActiveSeason";
import ModalShell from "@shared/components/ModalShell";
import { BackBtn, PageContainer, PageHeader } from "@shared/components/PageLayout/styles";
import StatusBanner from "@shared/components/StatusBanner";
import { appLog } from "@shared/utils/logger";
import { useNavigate, useSearchParams } from "react-router";
import { RxDatabaseProvider, useLiveRxQuery } from "rxdb/plugins/react";

import { type BallgameDb, getDb } from "@storage/db";
import { generateTeamId } from "@storage/generateId";
import { fnv1a } from "@storage/hash";
import type { TeamRecord } from "@storage/types";

import { validateAllSteps, validateWizardStep } from "../../wizard/validateWizardState";
import type { WizardState } from "../../wizard/wizardReducer";
import {
  clearWizardState,
  loadWizardState,
  makeInitialState,
  saveWizardState,
  wizardReducer,
} from "../../wizard/wizardReducer";
import { Step1, Step2, Step3, Step5, Step6 } from "./steps";
import {
  AbandonDialog,
  AbandonDialogActions,
  ActionButton,
  BlockedActions,
  DangerButton,
  FooterActions,
  PageTitle,
  SecondaryButton,
} from "./styles";

// ---------------------------------------------------------------------------
// Main wizard component
// ---------------------------------------------------------------------------

const STEP_LABELS: Record<number, string> = {
  1: "Format",
  2: "Teams",
  3: "Rules",
  5: "Seed",
  6: "Review",
};

function LeagueSetupWizardInner(): React.ReactElement {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { activeSeason, loading } = useActiveSeason();
  const modeParam = searchParams.get("mode");
  const requestedTeamMode: WizardState["teamMode"] | null =
    modeParam === "allAutogen" ? "allAutogen" : null;

  const customTeamsQuery = React.useMemo(() => ({ selector: {} }), []);
  const { results: customTeamResults } = useLiveRxQuery<TeamRecord>({
    collection: "teams",
    query: customTeamsQuery,
  });
  const customTeams = React.useMemo(
    () =>
      customTeamResults
        .map((d) => d.toJSON() as unknown as TeamRecord)
        .filter((team) => team.metadata?.archived !== true)
        .map((team) => ({ id: team.id, name: team.name })),
    [customTeamResults],
  );

  const [state, dispatch] = React.useReducer(wizardReducer, undefined, () => {
    const base = loadWizardState() ?? makeInitialState();
    if (requestedTeamMode !== "allAutogen") return base;
    const initialState: WizardState = {
      ...base,
      teamMode: "allAutogen",
      userCustomTeamId: null,
    };
    return initialState;
  });

  React.useEffect(() => {
    if (requestedTeamMode !== "allAutogen" || state.teamMode === "allAutogen") return;
    dispatch({ type: "SET_TEAM_MODE", mode: "allAutogen" });
    dispatch({ type: "SET_USER_TEAM", customTeamId: null });
  }, [requestedTeamMode, state.teamMode]);

  const [creating, setCreating] = React.useState(false);
  const [createError, setCreateError] = React.useState<string | null>(null);
  const [showAbandonDialog, setShowAbandonDialog] = React.useState(false);
  const abandonDialogRef = React.useRef<HTMLDialogElement>(null);

  React.useEffect(() => {
    saveWizardState(state);
  }, [state]);

  React.useEffect(() => {
    const dialog = abandonDialogRef.current;
    if (!dialog) return;
    if (showAbandonDialog) {
      if (!dialog.open) dialog.showModal();
    } else {
      if (dialog.open) dialog.close();
    }
  }, [showAbandonDialog]);

  const handleClose = React.useCallback(() => {
    navigate(-1);
  }, [navigate]);

  const handleCreateSeason = React.useCallback(async () => {
    setCreateError(null);
    setCreating(true);
    try {
      let season;
      if (state.teamMode === "allAutogen") {
        season = await quickStart({
          masterSeed: state.masterSeed,
          autogenSeed: state.autogenSeed,
          seasonName: state.seasonName.trim() || `Season ${new Date().getFullYear()}`,
          dhEnabled: state.leagues[0]?.dhEnabled ?? true,
          autogenOptions: {
            count: 8,
            theme: state.autogenTheme,
            parity:
              state.autogenParity <= 25
                ? "random"
                : state.autogenParity <= 75
                  ? "balanced"
                  : "mixed",
          },
        });
      } else {
        // Mixed or handpick: selectedTeamIds are the user's custom teams.
        // For mixed mode, fill remaining slots (up to 8) with autogenerated teams.
        const db = await getDb();
        const ctStore = makeCustomTeamStore(() => Promise.resolve(db));
        const allTeamIds = [...state.selectedTeamIds];

        if (state.teamMode === "mixed") {
          const slotsNeeded = 8 - allTeamIds.length;
          if (slotsNeeded > 0) {
            const autogenSubSeed = state.autogenSeed ?? fnv1a(`${state.masterSeed}:autogen:mixed`);
            const generated = generateLeagueTeams({
              count: slotsNeeded,
              theme: state.autogenTheme,
              parity:
                state.autogenParity <= 25
                  ? "random"
                  : state.autogenParity <= 75
                    ? "balanced"
                    : "mixed",
              masterSeed: state.masterSeed,
              autogenSubSeed,
              rosterMinimums: { lineup: 9, bench: 3, startingPitchers: 5, reliefPitchers: 3 },
              idFactory: { teamId: () => generateTeamId() },
            });
            for (const gen of generated) {
              const actualId = await ctStore.createCustomTeam(
                {
                  name: gen.name,
                  abbreviation: gen.abbreviation,
                  nickname: gen.nickname,
                  city: gen.city,
                  slug: gen.slug,
                  roster: {
                    lineup: gen.roster.lineup,
                    bench: gen.roster.bench,
                    pitchers: gen.roster.pitchers,
                  },
                  metadata: gen.metadata,
                  autogen: gen.autogen,
                  statsProfile: gen.statsProfile,
                },
                { id: gen.id },
              );
              allTeamIds.push(actualId); // use returned id (may differ from gen.id on reuse)
            }
          }
        }

        season = await createSeason({
          name: state.seasonName.trim() || `Season ${new Date().getFullYear()}`,
          masterSeed: state.masterSeed,
          preset: "mini",
          seasonLength: "sprint",
          leagues: state.leagues.map((l) => ({
            id: l.id,
            name: l.name,
            teamIds: allTeamIds,
            dhEnabled: l.dhEnabled,
          })),
          userCustomTeamId: state.userCustomTeamId,
        });
      }
      clearWizardState();
      navigate(`/leagues/${season.id}`);
    } catch (err) {
      setCreateError(err instanceof Error ? err.message : "Failed to create season.");
      setCreating(false);
    }
  }, [state, navigate]);

  const step6Errors = React.useMemo(
    () => (state.step === 6 ? validateAllSteps(state) : []),
    [state],
  );
  const currentStepErrors = React.useMemo(() => validateWizardStep(state), [state]);

  const isFirstStep = state.step === 1;
  const isLastStep = state.step === 6;

  const footer = (
    <FooterActions>
      <SecondaryButton
        type="button"
        onClick={() => dispatch({ type: "PREV_STEP" })}
        disabled={isFirstStep || creating}
      >
        ← Back
      </SecondaryButton>
      {!isLastStep && (
        <ActionButton
          type="button"
          data-testid="wizard-next-button"
          onClick={() => dispatch({ type: "NEXT_STEP" })}
          disabled={creating || currentStepErrors.length > 0}
        >
          Next →
        </ActionButton>
      )}
    </FooterActions>
  );

  const stepLabel = STEP_LABELS[state.step] ?? `Step ${state.step}`;
  const title = `New Season — ${stepLabel}`;

  if (!loading && activeSeason !== null) {
    return (
      <>
        <PageContainer data-testid="league-setup-wizard">
          <PageHeader>
            <BackBtn
              type="button"
              onClick={() => navigate("/leagues")}
              aria-label="Back to leagues"
            >
              ← Leagues
            </BackBtn>
          </PageHeader>
          <PageTitle>New Season</PageTitle>
          <StatusBanner variant="warn" title="Active season in progress">
            You already have an active season. Finish or abandon it before creating a new one.
          </StatusBanner>
          <BlockedActions>
            <ActionButton type="button" onClick={() => navigate(`/leagues/${activeSeason.id}`)}>
              Continue current season
            </ActionButton>
            <DangerButton type="button" onClick={() => setShowAbandonDialog(true)}>
              Abandon season
            </DangerButton>
          </BlockedActions>
        </PageContainer>

        <AbandonDialog
          ref={abandonDialogRef}
          role="alertdialog"
          aria-labelledby="abandon-title"
          aria-describedby="abandon-desc"
        >
          <h2 id="abandon-title" style={{ margin: "0 0 12px" }}>
            Abandon &apos;{activeSeason.name}&apos;?
          </h2>
          <p id="abandon-desc" style={{ margin: 0 }}>
            In-flight games are kept for reference but the season won&apos;t continue. This cannot
            be undone.
          </p>
          <AbandonDialogActions>
            <SecondaryButton type="button" onClick={() => setShowAbandonDialog(false)}>
              Cancel
            </SecondaryButton>
            <DangerButton
              type="button"
              onClick={async () => {
                if (!activeSeason) return;
                const db = await getDb();
                const seasonDoc = await db.seasons.findOne(activeSeason.id).exec();
                if (seasonDoc) {
                  await seasonDoc.patch({ status: "abandoned", completedAt: Date.now() });
                }
                setShowAbandonDialog(false);
              }}
            >
              Abandon
            </DangerButton>
          </AbandonDialogActions>
        </AbandonDialog>
      </>
    );
  }

  const stepContent = (() => {
    switch (state.step) {
      case 1:
        return <Step1 state={state} dispatch={dispatch} />;
      case 2:
        return (
          <Step2
            state={state}
            dispatch={dispatch}
            customTeams={customTeams}
            errors={currentStepErrors}
          />
        );
      case 3:
        return <Step3 state={state} dispatch={dispatch} />;
      case 5:
        return <Step5 state={state} dispatch={dispatch} errors={currentStepErrors} />;
      case 6:
        return (
          <Step6
            state={state}
            dispatch={dispatch}
            onCreateSeason={handleCreateSeason}
            creating={creating}
            errors={[...(createError !== null ? [createError] : []), ...step6Errors]}
            customTeams={customTeams}
          />
        );
      default:
        return null;
    }
  })();

  return (
    <div data-testid="league-setup-wizard">
      <ModalShell title={title} onClose={handleClose} open footer={footer}>
        {stepContent}
      </ModalShell>
    </div>
  );
}

export default function LeagueSetupWizard(): React.ReactElement {
  const [db, setDb] = React.useState<BallgameDb | null>(null);

  React.useEffect(() => {
    getDb()
      .then(setDb)
      .catch((err: unknown) => appLog.error("[LeagueSetupWizard] DB init failed:", err));
  }, []);

  if (!db) {
    return (
      <div data-testid="league-setup-wizard" style={{ padding: "24px" }}>
        Loading…
      </div>
    );
  }

  return (
    <RxDatabaseProvider
      database={db as unknown as Parameters<typeof RxDatabaseProvider>[0]["database"]}
    >
      <LeagueSetupWizardInner />
    </RxDatabaseProvider>
  );
}
