import * as React from "react";

import EmptyState from "@shared/components/EmptyState";
import { BackBtn, PageContainer, PageHeader } from "@shared/components/PageLayout/styles";
import { appLog } from "@shared/utils/logger";
import { useNavigate } from "react-router";
import { RxDatabaseProvider, useLiveRxQuery } from "rxdb/plugins/react";

import type { BallgameDb } from "@storage/db";
import { getDb } from "@storage/db";
import type { SeasonRecord, TeamRecord } from "@storage/types";

import {
  ActionLink,
  BodyText,
  ContinueCard,
  ContinueSub,
  ContinueTitle,
  HubGrid,
  LoadingState,
  PageTitle,
  PastSeasonsDetails,
  SeasonItemLink,
  SeasonItemMeta,
  SeasonList,
  SeasonListItem,
  SecondaryLink,
  SectionActions,
  SectionCard,
} from "./styles";

const ALL_SEASONS_QUERY = { selector: {}, sort: [{ createdAt: "desc" as const }] };
const ALL_TEAMS_QUERY = { selector: {} };

const LeaguesHubPageInner: React.FunctionComponent = () => {
  const navigate = useNavigate();

  const { results: seasonResults, loading: seasonsLoading } = useLiveRxQuery<SeasonRecord>({
    collection: "seasons",
    query: ALL_SEASONS_QUERY,
  });

  const { results: teamResults, loading: teamsLoading } = useLiveRxQuery<TeamRecord>({
    collection: "teams",
    query: ALL_TEAMS_QUERY,
  });

  const seasons = React.useMemo(
    () => seasonResults.map((d) => d.toJSON() as unknown as SeasonRecord),
    [seasonResults],
  );

  const loading = seasonsLoading || teamsLoading;
  const hasCustomTeams = teamResults.length > 0;

  const activeSeason = seasons.find((s) => s.status === "active") ?? null;
  const historicalSeasons = seasons.filter((s) => s.status !== "active");
  const hasAnySeasons = seasons.length > 0;

  if (loading) {
    return (
      <PageContainer data-testid="leagues-hub">
        <PageHeader>
          <BackBtn type="button" onClick={() => navigate(-1)} aria-label="Go back">
            ← Back
          </BackBtn>
        </PageHeader>
        <PageTitle>Leagues</PageTitle>
        <LoadingState>Loading…</LoadingState>
      </PageContainer>
    );
  }

  // State 1 — Zero seasons, zero custom teams
  if (!hasAnySeasons && !hasCustomTeams) {
    return (
      <PageContainer data-testid="leagues-hub">
        <PageHeader>
          <BackBtn type="button" onClick={() => navigate(-1)} aria-label="Go back">
            ← Back
          </BackBtn>
        </PageHeader>
        <PageTitle>Leagues</PageTitle>
        <EmptyState
          title="Welcome to League Mode"
          body="Welcome to League Mode. Build a team to start your first season — or skip ahead with all-autogenerated teams."
        />
        <SectionActions>
          <ActionLink
            href="/teams/new"
            onClick={(e: React.MouseEvent) => {
              e.preventDefault();
              navigate("/teams/new");
            }}
            data-testid="hub-build-first-team"
          >
            Build your first team
          </ActionLink>
          <SecondaryLink
            href="/leagues/new?mode=allAutogen"
            onClick={(e: React.MouseEvent) => {
              e.preventDefault();
              navigate("/leagues/new?mode=allAutogen");
            }}
            data-testid="hub-start-autogen"
          >
            Start a Season (all autogenerated)
          </SecondaryLink>
        </SectionActions>
      </PageContainer>
    );
  }

  // State 2 — Zero seasons, has custom teams
  if (!hasAnySeasons && hasCustomTeams) {
    return (
      <PageContainer data-testid="leagues-hub">
        <PageHeader>
          <BackBtn type="button" onClick={() => navigate(-1)} aria-label="Go back">
            ← Back
          </BackBtn>
        </PageHeader>
        <PageTitle>Leagues</PageTitle>
        <EmptyState title="No seasons yet" body="You haven't started a season yet. Create one →" />
        <SectionActions>
          <ActionLink
            href="/leagues/new"
            onClick={(e: React.MouseEvent) => {
              e.preventDefault();
              navigate("/leagues/new");
            }}
            data-testid="hub-start-season"
          >
            Start a Season
          </ActionLink>
          <SecondaryLink
            href="/teams"
            onClick={(e: React.MouseEvent) => {
              e.preventDefault();
              navigate("/teams");
            }}
            data-testid="hub-manage-teams"
          >
            Manage teams
          </SecondaryLink>
        </SectionActions>
      </PageContainer>
    );
  }

  // State 5 — Zero active + N historical
  if (!activeSeason && historicalSeasons.length > 0) {
    const lastSeason = historicalSeasons[0];
    return (
      <PageContainer data-testid="leagues-hub">
        <PageHeader>
          <BackBtn type="button" onClick={() => navigate(-1)} aria-label="Go back">
            ← Back
          </BackBtn>
        </PageHeader>
        <PageTitle>Leagues</PageTitle>
        <BodyText>Welcome back. Start a new season or revisit your champions.</BodyText>
        <SectionActions>
          <ActionLink
            href="/leagues/new"
            onClick={(e: React.MouseEvent) => {
              e.preventDefault();
              navigate("/leagues/new");
            }}
            data-testid="hub-start-new-season"
          >
            Start a New Season
          </ActionLink>
          <SecondaryLink
            href={`/leagues/${lastSeason.id}`}
            onClick={(e: React.MouseEvent) => {
              e.preventDefault();
              navigate(`/leagues/${lastSeason.id}`);
            }}
            data-testid="hub-view-champion"
          >
            View champion: {lastSeason.name}
          </SecondaryLink>
        </SectionActions>
      </PageContainer>
    );
  }

  // State 3 — Active season, no historical
  // State 4 — Active season + historical
  if (activeSeason) {
    const progressText = `Continue: ${activeSeason.name} · day ${activeSeason.currentGameDay} / 30`;
    const progressId = "hub-season-progress";

    return (
      <PageContainer data-testid="leagues-hub">
        <PageHeader>
          <BackBtn type="button" onClick={() => navigate(-1)} aria-label="Go back">
            ← Back
          </BackBtn>
        </PageHeader>
        <PageTitle>Leagues</PageTitle>
        <HubGrid>
          <ContinueCard
            href={`/leagues/${activeSeason.id}`}
            onClick={(e: React.MouseEvent) => {
              e.preventDefault();
              navigate(`/leagues/${activeSeason.id}`);
            }}
            aria-describedby={progressId}
            data-testid="hub-continue-card"
          >
            <ContinueTitle>{progressText}</ContinueTitle>
            <ContinueSub id={progressId}>
              {activeSeason.preset} · {activeSeason.seasonLength} season
            </ContinueSub>
          </ContinueCard>

          <SectionCard>
            <SectionActions>
              <SecondaryLink
                href="/teams"
                onClick={(e: React.MouseEvent) => {
                  e.preventDefault();
                  navigate("/teams");
                }}
                data-testid="hub-view-teams"
              >
                View teams
              </SecondaryLink>
            </SectionActions>

            {historicalSeasons.length > 0 && (
              <PastSeasonsDetails data-testid="hub-past-seasons">
                <summary>Past seasons ({historicalSeasons.length})</summary>
                <SeasonList>
                  {historicalSeasons.map((s) => (
                    <SeasonListItem key={s.id}>
                      <SeasonItemLink
                        href={`/leagues/${s.id}`}
                        onClick={(e: React.MouseEvent) => {
                          e.preventDefault();
                          navigate(`/leagues/${s.id}`);
                        }}
                      >
                        {s.name}
                      </SeasonItemLink>
                      <SeasonItemMeta>{s.status}</SeasonItemMeta>
                    </SeasonListItem>
                  ))}
                </SeasonList>
              </PastSeasonsDetails>
            )}
          </SectionCard>
        </HubGrid>
      </PageContainer>
    );
  }

  // Fallback — should not normally be reached
  return (
    <PageContainer data-testid="leagues-hub">
      <PageHeader>
        <BackBtn type="button" onClick={() => navigate(-1)} aria-label="Go back">
          ← Back
        </BackBtn>
      </PageHeader>
      <PageTitle>Leagues</PageTitle>
      <LoadingState>Loading…</LoadingState>
    </PageContainer>
  );
};

const LeaguesHubPage: React.FunctionComponent = () => {
  const [db, setDb] = React.useState<BallgameDb | null>(null);

  React.useEffect(() => {
    getDb()
      .then(setDb)
      .catch((err: unknown) => appLog.error("[LeaguesHubPage] DB init failed:", err));
  }, []);

  if (!db) {
    return (
      <PageContainer data-testid="leagues-hub">
        <PageHeader>
          <BackBtn type="button" disabled aria-label="Go back">
            ← Back
          </BackBtn>
        </PageHeader>
        <PageTitle>Leagues</PageTitle>
        <LoadingState>Loading…</LoadingState>
      </PageContainer>
    );
  }

  return (
    <RxDatabaseProvider
      database={db as unknown as Parameters<typeof RxDatabaseProvider>[0]["database"]}
    >
      <LeaguesHubPageInner />
    </RxDatabaseProvider>
  );
};

export default LeaguesHubPage;
