import * as React from "react";

import type { WizardAction, WizardState } from "../../../wizard/wizardReducer";
import {
  ActionButton,
  ActionRow,
  ErrorList,
  ErrorText,
  FieldGroup,
  FieldLabel,
  FieldSelect,
  RadioOption,
  RadioRow,
  StepContainer,
  StepTitle,
  SummaryKey,
  SummaryTable,
  SummaryValue,
} from "../styles";

export interface Step6Props {
  state: WizardState;
  dispatch: React.Dispatch<WizardAction>;
  onCreateSeason: () => void;
  creating: boolean;
  errors: string[];
  customTeams: Array<{ id: string; name: string }>;
}

export function Step6({
  state,
  dispatch,
  onCreateSeason,
  creating,
  errors,
  customTeams,
}: Step6Props): React.ReactElement {
  const teamModeLabel =
    state.teamMode === "allAutogen"
      ? "All autogenerated"
      : state.teamMode === "mixed"
        ? `Mixed (${state.selectedTeamIds.length} handpicked)`
        : `Handpicked (${state.selectedTeamIds.length} teams)`;

  const teamNameById = React.useMemo(() => {
    const map: Record<string, string> = {};
    for (const t of customTeams) {
      map[t.id] = t.name;
    }
    return map;
  }, [customTeams]);

  return (
    <StepContainer>
      <StepTitle>Review &amp; Create</StepTitle>
      <SummaryTable>
        <SummaryKey>Season name</SummaryKey>
        <SummaryValue>{state.seasonName || <em>unnamed</em>}</SummaryValue>
        <SummaryKey>Preset</SummaryKey>
        <SummaryValue>Mini · Sprint</SummaryValue>
        <SummaryKey>Leagues</SummaryKey>
        <SummaryValue>{state.leagueCount}</SummaryValue>
        <SummaryKey>Teams</SummaryKey>
        <SummaryValue>{teamModeLabel}</SummaryValue>
        {state.teamMode !== "handpick" && (
          <>
            <SummaryKey>Theme</SummaryKey>
            <SummaryValue>
              {state.autogenTheme.charAt(0).toUpperCase() + state.autogenTheme.slice(1)}
            </SummaryValue>
          </>
        )}
        {state.leagues.map((league) => (
          <React.Fragment key={league.id}>
            <SummaryKey>{league.name} DH</SummaryKey>
            <SummaryValue>{league.dhEnabled ? "On" : "Off"}</SummaryValue>
          </React.Fragment>
        ))}
        <SummaryKey>Master seed</SummaryKey>
        <SummaryValue>{state.masterSeed || <em>empty</em>}</SummaryValue>
      </SummaryTable>

      <FieldGroup>
        <div>
          <FieldLabel>Which team will you manage?</FieldLabel>
          {state.teamMode === "allAutogen" ? (
            <RadioRow>
              <RadioOption>
                <input type="radio" checked readOnly />
                I&apos;ll pick after the season starts (observer mode)
              </RadioOption>
            </RadioRow>
          ) : (
            <FieldSelect
              value={state.userCustomTeamId ?? ""}
              onChange={(e) =>
                dispatch({
                  type: "SET_USER_TEAM",
                  customTeamId: e.target.value || null,
                })
              }
              aria-label="Select your team"
              data-testid="managed-team-select"
            >
              <option value="">— Select a team —</option>
              {state.selectedTeamIds.map((id) => (
                <option key={id} value={id}>
                  {teamNameById[id] ?? id}
                </option>
              ))}
            </FieldSelect>
          )}
        </div>
      </FieldGroup>

      {errors.length > 0 && (
        <ErrorList aria-live="polite" role="status">
          {errors.map((err) => (
            <ErrorText key={err}>⚠ {err}</ErrorText>
          ))}
        </ErrorList>
      )}
      <ActionRow>
        <ActionButton
          type="button"
          onClick={onCreateSeason}
          disabled={creating || errors.length > 0}
          data-testid="create-season-button"
        >
          {creating ? "Creating…" : "Create Season"}
        </ActionButton>
      </ActionRow>
    </StepContainer>
  );
}
